export default {
    TOGGLE_NAV:'TOGGLE_NAV',
    TOGGLE_INFO:'TOGGLE_INFO',
    TOGGLE_SIDEBAR:'TOGGLE_SIDEBAR',
    HANDLE_NOTES_CHANGE:'HANDLE_NOTES_CHANGE',
    ADD_NOTE:'ADD_NOTE',
    REMOVE_NOTE:'REMOVE_NOTE',
    RESTORE_NOTE:'RESTORE_NOTE',
    DELETE_NOTE:'DELETE_NOTE',
    ADD_TAG:'ADD_TAG',
    REMOVE_TAG:'REMOVE_TAG',
    CHANGE_QUERY:'CHANGE_QUERY',
    CHANGE_NOTE:'CHANGE_NOTE',
};
